# generated by datamodel-codegen:
#   filename:  order-queryresponse.json
#   timestamp: 2022-07-01T22:35:17+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel


class Source(BaseModel):
    ID: Optional[Optional[str]] = None
    Name: Optional[Optional[str]] = None


class Destination(BaseModel):
    ID: Optional[Optional[str]] = None
    Name: Optional[Optional[str]] = None


class Log(BaseModel):
    ID: Optional[Optional[str]] = None
    AttemptID: Optional[Optional[str]] = None


class Message(BaseModel):
    ID: Optional[Optional[float]] = None


class Transmission(BaseModel):
    ID: Optional[Optional[float]] = None


class Meta(BaseModel):
    DataModel: str
    EventType: str
    EventDateTime: Optional[Optional[str]] = None
    Test: Optional[Optional[bool]] = None
    Source: Optional[Source] = None
    Destinations: Optional[List[Destination]] = None
    Logs: Optional[List[Log]] = None
    Message: Optional[Message] = None
    Transmission: Optional[Transmission] = None
    FacilityCode: Optional[Optional[str]] = None


class Identifier(BaseModel):
    ID: Optional[Optional[str]] = None
    IDType: Optional[Optional[str]] = None


class Patient(BaseModel):
    Identifiers: Optional[List[Identifier]] = None


class Visit(BaseModel):
    VisitNumber: Optional[Optional[str]] = None


class Specimen(BaseModel):
    Source: Optional[Optional[str]] = None
    BodySite: Optional[Optional[str]] = None
    ID: Optional[Optional[str]] = None


class Procedure(BaseModel):
    Code: Optional[Optional[str]] = None
    Codeset: Optional[Optional[str]] = None
    Description: Optional[Optional[str]] = None


class Address(BaseModel):
    StreetAddress: Optional[Optional[str]] = None
    City: Optional[Optional[str]] = None
    State: Optional[Optional[str]] = None
    ZIP: Optional[Optional[str]] = None
    County: Optional[Optional[str]] = None
    Country: Optional[Optional[str]] = None


class PhoneNumber(BaseModel):
    Office: Optional[Optional[str]] = None


class Location(BaseModel):
    Type: Optional[Optional[str]] = None
    Facility: Optional[Optional[str]] = None
    Department: Optional[Optional[str]] = None
    Room: Optional[Optional[str]] = None


class Provider(BaseModel):
    NPI: Optional[Optional[str]] = None
    ID: Optional[Optional[str]] = None
    IDType: Optional[Optional[str]] = None
    FirstName: Optional[Optional[str]] = None
    LastName: Optional[Optional[str]] = None
    Credentials: Optional[List] = None
    Address: Optional[Address] = None
    EmailAddresses: Optional[List] = None
    PhoneNumber: Optional[PhoneNumber] = None
    Location: Optional[Location] = None


class Address1(BaseModel):
    StreetAddress: Optional[Optional[str]] = None
    City: Optional[Optional[str]] = None
    State: Optional[Optional[str]] = None
    ZIP: Optional[Optional[str]] = None
    County: Optional[Optional[str]] = None
    Country: Optional[Optional[str]] = None


class PhoneNumber1(BaseModel):
    Office: Optional[Optional[str]] = None


class Location1(BaseModel):
    Type: Optional[Optional[str]] = None
    Facility: Optional[Optional[str]] = None
    Department: Optional[Optional[str]] = None
    Room: Optional[Optional[str]] = None


class ResultCopyProvider(BaseModel):
    NPI: Optional[Optional[str]] = None
    ID: Optional[Optional[str]] = None
    IDType: Optional[Optional[str]] = None
    FirstName: Optional[Optional[str]] = None
    LastName: Optional[Optional[str]] = None
    Credentials: Optional[List] = None
    Address: Optional[Address1] = None
    EmailAddresses: Optional[List] = None
    PhoneNumber: Optional[PhoneNumber1] = None
    Location: Optional[Location1] = None


class Address2(BaseModel):
    StreetAddress: Optional[Optional[str]] = None
    City: Optional[Optional[str]] = None
    State: Optional[Optional[str]] = None
    ZIP: Optional[Optional[str]] = None
    County: Optional[Optional[str]] = None
    Country: Optional[Optional[str]] = None


class OrderingFacility(BaseModel):
    Name: Optional[Optional[str]] = None
    Address: Optional[Address2] = None
    PhoneNumber: Optional[Optional[str]] = None


class Diagnose(BaseModel):
    Code: Optional[Optional[str]] = None
    Codeset: Optional[Optional[str]] = None
    Name: Optional[Optional[str]] = None
    Type: Optional[Optional[str]] = None
    DocumentedDateTime: Optional[Optional[str]] = None


class ClinicalInfoItem(BaseModel):
    Code: Optional[Optional[str]] = None
    Codeset: Optional[Optional[str]] = None
    Description: Optional[Optional[str]] = None
    Value: Optional[Optional[str]] = None
    Units: Optional[Optional[str]] = None
    Abbreviation: Optional[Optional[str]] = None
    Notes: Optional[List] = None


class Order(BaseModel):
    Patient: Optional[Patient] = None
    Visit: Optional[Visit] = None
    ID: Optional[Optional[str]] = None
    ApplicationOrderID: Optional[Optional[str]] = None
    Status: Optional[Optional[str]] = None
    TransactionDateTime: Optional[Optional[str]] = None
    CollectionDateTime: Optional[Optional[str]] = None
    Specimen: Optional[Specimen] = None
    Procedure: Optional[Procedure] = None
    Provider: Optional[Provider] = None
    ResultCopyProviders: Optional[List[ResultCopyProvider]] = None
    OrderingFacility: Optional[OrderingFacility] = None
    Priority: Optional[Optional[str]] = None
    Comments: Optional[Optional[str]] = None
    Notes: Optional[List] = None
    Diagnoses: Optional[List[Diagnose]] = None
    ClinicalInfo: Optional[List[ClinicalInfoItem]] = None


class Model(BaseModel):
    Meta: Meta
    Orders: Optional[List[Order]] = None
