# generated by datamodel-codegen:
#   filename:  order-query.json
#   timestamp: 2022-07-01T22:35:06+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel


class Source(BaseModel):
    ID: Optional[Optional[str]] = None
    Name: Optional[Optional[str]] = None


class Destination(BaseModel):
    ID: Optional[Optional[str]] = None
    Name: Optional[Optional[str]] = None


class Log(BaseModel):
    ID: Optional[Optional[str]] = None
    AttemptID: Optional[Optional[str]] = None


class Message(BaseModel):
    ID: Optional[Optional[float]] = None


class Transmission(BaseModel):
    ID: Optional[Optional[float]] = None


class Meta(BaseModel):
    DataModel: str
    EventType: str
    EventDateTime: Optional[Optional[str]] = None
    Test: Optional[Optional[bool]] = None
    Source: Optional[Source] = None
    Destinations: Optional[List[Destination]] = None
    Logs: Optional[List[Log]] = None
    Message: Optional[Message] = None
    Transmission: Optional[Transmission] = None
    FacilityCode: Optional[Optional[str]] = None


class Identifier(BaseModel):
    ID: Optional[Optional[str]] = None
    IDType: Optional[Optional[str]] = None


class Patient(BaseModel):
    Identifiers: Optional[List[Identifier]] = None


class Procedure(BaseModel):
    Code: Optional[Optional[str]] = None
    Codeset: Optional[Optional[str]] = None


class Model(BaseModel):
    Meta: Meta
    Patients: Optional[List[Patient]] = None
    VisitNumbers: Optional[List] = None
    StartDateTime: Optional[Optional[str]] = None
    EndDateTime: Optional[Optional[str]] = None
    OrderIDs: Optional[List] = None
    Procedures: Optional[List[Procedure]] = None
